INPUT_VIDEO = <please select a video file as INPUT_VIDEO>

# We need Bash's process substitution operator >()
# because we want to convert the files back to a
# cooked format, because raw takes a serious amount
# of space. It is of course also possible to use
# FIFO:s (if you know what you are doing).
SHELL = bash

DRAFT =
#DRAFT = -d
# Useful for better performance when not working
# with colours or not caring about colours.

FFMPEG_ARGS = -c:v libx264 -preset veryslow -crf 0 -pix_fmt yuv444p
#             ↑~~~~~~~~~~~ ↑~~~~~~~~~~~~~~~ ↑~~~~~~~~~~~~~~~~~~~~~~
#             │            │                │
#             │            │                └──── Lossless
#             │            │
#             │            └──── High compression
#             │
#             └──── H.264, a lossless-capable codec
.PHONY: all

all: $(INPUT_VIDEO)
	framerate=$$(ffprobe -v quiet -show_streams -select_streams v - < "$(INPUT_VIDEO)" | \
	             grep '^r_frame_rate=' | cut -d = -f 2) && \
	blind-from-video -L $(DRAFT) "$(INPUT_VIDEO)" - | \
	blind-split -L \
